// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friends.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFriendRequest = `-- name: CreateFriendRequest :execrows
INSERT INTO friend_requests (
    requester_id,
    target_id,
    created_at
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT DO NOTHING
`

type CreateFriendRequestParams struct {
	RequesterID uuid.UUID
	TargetID    uuid.UUID
	CreatedAt   time.Time
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createFriendRequest, arg.RequesterID, arg.TargetID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createFriendship = `-- name: CreateFriendship :execrows

INSERT INTO friendships(
    user_id,
    friend_id,
    created_at
)
VALUES(
    $1,
    $2,
    $3
)
ON CONFLICT DO NOTHING
`

type CreateFriendshipParams struct {
	UserID    uuid.UUID
	FriendID  uuid.UUID
	CreatedAt time.Time
}

// -----
func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createFriendship, arg.UserID, arg.FriendID, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :exec
DELETE FROM friend_requests
WHERE
(requester_id = $1 AND target_id = $2)
OR
(requester_id = $2 AND target_id = $1)
`

type DeleteFriendRequestParams struct {
	RequesterID uuid.UUID
	TargetID    uuid.UUID
}

func (q *Queries) DeleteFriendRequest(ctx context.Context, arg DeleteFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendRequest, arg.RequesterID, arg.TargetID)
	return err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE user_id = $1
    AND friend_id = $2
`

type DeleteFriendshipParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendship, arg.UserID, arg.FriendID)
	return err
}

const friendRequestExists = `-- name: FriendRequestExists :one
SELECT EXISTS (
    SELECT 1
    FROM friend_requests
    WHERE
        (requester_id = $1 AND target_id $2)
        OR
        (requester_id = $2 AND target_id = $1)
)
`

type FriendRequestExistsParams struct {
	RequesterID uuid.UUID
	Column2     interface{}
}

func (q *Queries) FriendRequestExists(ctx context.Context, arg FriendRequestExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, friendRequestExists, arg.RequesterID, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const friendshipExists = `-- name: FriendshipExists :one
SELECT EXISTS (
    SELECT 1
    FROM friendships
    WHERE user_id = $1
        AND friend_id = $2
)
`

type FriendshipExistsParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) FriendshipExists(ctx context.Context, arg FriendshipExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, friendshipExists, arg.UserID, arg.FriendID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFriendsByUserID = `-- name: ListFriendsByUserID :many
SELECT
    u.id,
    u.username,
    u.created_at
FROM friendships f
JOIN users u
    ON u.id = CASE
        WHEN f.user_id = $1 THEN f.friend_id
        ELSE f.user_id
    END
WHERE f.user_id = $1
   OR f.friend_id = $1
ORDER BY u.username
`

type ListFriendsByUserIDRow struct {
	ID        uuid.UUID
	Username  string
	CreatedAt time.Time
}

func (q *Queries) ListFriendsByUserID(ctx context.Context, userID uuid.UUID) ([]ListFriendsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listFriendsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsByUserIDRow
	for rows.Next() {
		var i ListFriendsByUserIDRow
		if err := rows.Scan(&i.ID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingFriendRequestsByUserID = `-- name: ListIncomingFriendRequestsByUserID :many
SELECT
    u.id,
    u.username,
    u.created_at
FROM friend_requests fr
JOIN users u
ON u.id = fr.requester_id
WHERE fr.target_id = $1
ORDER BY fr.created_at DESC
`

type ListIncomingFriendRequestsByUserIDRow struct {
	ID        uuid.UUID
	Username  string
	CreatedAt time.Time
}

func (q *Queries) ListIncomingFriendRequestsByUserID(ctx context.Context, targetID uuid.UUID) ([]ListIncomingFriendRequestsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listIncomingFriendRequestsByUserID, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomingFriendRequestsByUserIDRow
	for rows.Next() {
		var i ListIncomingFriendRequestsByUserIDRow
		if err := rows.Scan(&i.ID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingFriendRequestsByUserID = `-- name: ListOutgoingFriendRequestsByUserID :many
SELECT
    u.id,
    u.username,
    u.created_at
FROM friend_requests fr
JOIN users u
    ON u.id = fr.target_id
WHERE fr.requester_id = $1
ORDER BY fr.created_at DESC
`

type ListOutgoingFriendRequestsByUserIDRow struct {
	ID        uuid.UUID
	Username  string
	CreatedAt time.Time
}

func (q *Queries) ListOutgoingFriendRequestsByUserID(ctx context.Context, requesterID uuid.UUID) ([]ListOutgoingFriendRequestsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listOutgoingFriendRequestsByUserID, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutgoingFriendRequestsByUserIDRow
	for rows.Next() {
		var i ListOutgoingFriendRequestsByUserIDRow
		if err := rows.Scan(&i.ID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
