// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    id,
    white_id,
    black_id,
    time_control,
    white_rating_before,
    black_rating_before,
    result
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    'pending'
)
RETURNING
    id,
    white_id,
    black_id,
    time_control,
    white_rating_before,
    black_rating_before,
    white_rating_after,
    black_rating_after,
    result,
    created_at,
    finished_at
`

type CreateMatchParams struct {
	ID                uuid.UUID
	WhiteID           uuid.UUID
	BlackID           uuid.UUID
	TimeControl       string
	WhiteRatingBefore int32
	BlackRatingBefore int32
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, createMatch,
		arg.ID,
		arg.WhiteID,
		arg.BlackID,
		arg.TimeControl,
		arg.WhiteRatingBefore,
		arg.BlackRatingBefore,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.WhiteID,
		&i.BlackID,
		&i.TimeControl,
		&i.WhiteRatingBefore,
		&i.BlackRatingBefore,
		&i.WhiteRatingAfter,
		&i.BlackRatingAfter,
		&i.Result,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishMatch = `-- name: FinishMatch :one
UPDATE matches
SET
    result = $2,
    white_rating_after = $3,
    black_rating_after = $4,
    finished_at = NOW()
WHERE id = $1
  AND result = 'pending'
RETURNING
    id,
    white_id,
    black_id,
    time_control,
    white_rating_before,
    black_rating_before,
    white_rating_after,
    black_rating_after,
    result,
    created_at,
    finished_at
`

type FinishMatchParams struct {
	ID               uuid.UUID
	Result           MatchResult
	WhiteRatingAfter sql.NullInt32
	BlackRatingAfter sql.NullInt32
}

func (q *Queries) FinishMatch(ctx context.Context, arg FinishMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, finishMatch,
		arg.ID,
		arg.Result,
		arg.WhiteRatingAfter,
		arg.BlackRatingAfter,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.WhiteID,
		&i.BlackID,
		&i.TimeControl,
		&i.WhiteRatingBefore,
		&i.BlackRatingBefore,
		&i.WhiteRatingAfter,
		&i.BlackRatingAfter,
		&i.Result,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getActiveMatchForPlayer = `-- name: GetActiveMatchForPlayer :one
SELECT
    id,
    white_id,
    black_id,
    time_control,
    white_rating_before,
    black_rating_before,
    white_rating_after,
    black_rating_after,
    result,
    created_at,
    finished_at
FROM matches
WHERE result = 'pending'
  AND (
      white_id = $1
      OR black_id = $1
  )
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveMatchForPlayer(ctx context.Context, whiteID uuid.UUID) (Match, error) {
	row := q.db.QueryRowContext(ctx, getActiveMatchForPlayer, whiteID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.WhiteID,
		&i.BlackID,
		&i.TimeControl,
		&i.WhiteRatingBefore,
		&i.BlackRatingBefore,
		&i.WhiteRatingAfter,
		&i.BlackRatingAfter,
		&i.Result,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getMatch = `-- name: GetMatch :one
SELECT
    id,
    white_id,
    black_id,
    time_control,
    white_rating_before,
    black_rating_before,
    white_rating_after,
    black_rating_after,
    result,
    created_at,
    finished_at
FROM matches
WHERE id = $1
`

func (q *Queries) GetMatch(ctx context.Context, id uuid.UUID) (Match, error) {
	row := q.db.QueryRowContext(ctx, getMatch, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.WhiteID,
		&i.BlackID,
		&i.TimeControl,
		&i.WhiteRatingBefore,
		&i.BlackRatingBefore,
		&i.WhiteRatingAfter,
		&i.BlackRatingAfter,
		&i.Result,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getMatchDetailsForPlayer = `-- name: GetMatchDetailsForPlayer :one
SELECT
    m.id,

    m.white_id,
    white_user.username AS white_username,
    m.white_rating_before,

    m.black_id,
    black_user.username AS black_username,
    m.black_rating_before,

    m.time_control,
    m.result,

    m.created_at,
    m.finished_at
FROM matches AS m
INNER JOIN users AS white_user
    ON white_user.id = m.white_id
INNER JOIN users AS black_user
    ON black_user.id = m.black_id
WHERE m.id = $1
  AND (
      m.white_id = $2
      OR m.black_id = $2
)
`

type GetMatchDetailsForPlayerParams struct {
	ID      uuid.UUID
	WhiteID uuid.UUID
}

type GetMatchDetailsForPlayerRow struct {
	ID                uuid.UUID
	WhiteID           uuid.UUID
	WhiteUsername     string
	WhiteRatingBefore int32
	BlackID           uuid.UUID
	BlackUsername     string
	BlackRatingBefore int32
	TimeControl       string
	Result            MatchResult
	CreatedAt         time.Time
	FinishedAt        sql.NullTime
}

func (q *Queries) GetMatchDetailsForPlayer(ctx context.Context, arg GetMatchDetailsForPlayerParams) (GetMatchDetailsForPlayerRow, error) {
	row := q.db.QueryRowContext(ctx, getMatchDetailsForPlayer, arg.ID, arg.WhiteID)
	var i GetMatchDetailsForPlayerRow
	err := row.Scan(
		&i.ID,
		&i.WhiteID,
		&i.WhiteUsername,
		&i.WhiteRatingBefore,
		&i.BlackID,
		&i.BlackUsername,
		&i.BlackRatingBefore,
		&i.TimeControl,
		&i.Result,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getMatchForPlayer = `-- name: GetMatchForPlayer :one
SELECT
    id,
    white_id,
    black_id,
    time_control,
    white_rating_before,
    black_rating_before,
    white_rating_after,
    black_rating_after,
    result,
    created_at,
    finished_at
FROM matches
WHERE id = $1
  AND (
      white_id = $2
      OR black_id = $2
)
`

type GetMatchForPlayerParams struct {
	ID      uuid.UUID
	WhiteID uuid.UUID
}

func (q *Queries) GetMatchForPlayer(ctx context.Context, arg GetMatchForPlayerParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, getMatchForPlayer, arg.ID, arg.WhiteID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.WhiteID,
		&i.BlackID,
		&i.TimeControl,
		&i.WhiteRatingBefore,
		&i.BlackRatingBefore,
		&i.WhiteRatingAfter,
		&i.BlackRatingAfter,
		&i.Result,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getMatchState = `-- name: GetMatchState :one
SELECT
    m.id,
    m.white_id,
    m.black_id,
    m.time_control,
    m.result,
    m.created_at,
    m.finished_at,
    mm.move_number,
    mm.fen_after,
    mm.white_time_ms,
    mm.black_time_ms
FROM matches m
LEFT JOIN match_moves mm
    ON mm.match_id = m.id
   AND mm.move_number = (
       SELECT MAX(move_number)
       FROM match_moves
       WHERE match_id = m.id
   )
WHERE m.id = $1
`

type GetMatchStateRow struct {
	ID          uuid.UUID
	WhiteID     uuid.UUID
	BlackID     uuid.UUID
	TimeControl string
	Result      MatchResult
	CreatedAt   time.Time
	FinishedAt  sql.NullTime
	MoveNumber  sql.NullInt32
	FenAfter    sql.NullString
	WhiteTimeMs sql.NullInt64
	BlackTimeMs sql.NullInt64
}

func (q *Queries) GetMatchState(ctx context.Context, id uuid.UUID) (GetMatchStateRow, error) {
	row := q.db.QueryRowContext(ctx, getMatchState, id)
	var i GetMatchStateRow
	err := row.Scan(
		&i.ID,
		&i.WhiteID,
		&i.BlackID,
		&i.TimeControl,
		&i.Result,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.MoveNumber,
		&i.FenAfter,
		&i.WhiteTimeMs,
		&i.BlackTimeMs,
	)
	return i, err
}

const getPlayerRecentMatches = `-- name: GetPlayerRecentMatches :many
SELECT
    m.id,
    m.white_id,
    white_user.username AS white_username,
    m.black_id,
    black_user.username AS black_username,
    m.time_control,
    m.white_rating_before,
    m.black_rating_before,
    m.white_rating_after,
    m.black_rating_after,
    m.result,
    m.created_at,
    m.finished_at
FROM matches AS m
INNER JOIN users AS white_user
    ON white_user.id = m.white_id
INNER JOIN users AS black_user
    ON black_user.id = m.black_id
WHERE
    (m.white_id = $1 OR m.black_id = $1)
    AND m.result <> 'pending'
ORDER BY m.finished_at DESC
LIMIT $2
`

type GetPlayerRecentMatchesParams struct {
	WhiteID uuid.UUID
	Limit   int32
}

type GetPlayerRecentMatchesRow struct {
	ID                uuid.UUID
	WhiteID           uuid.UUID
	WhiteUsername     string
	BlackID           uuid.UUID
	BlackUsername     string
	TimeControl       string
	WhiteRatingBefore int32
	BlackRatingBefore int32
	WhiteRatingAfter  sql.NullInt32
	BlackRatingAfter  sql.NullInt32
	Result            MatchResult
	CreatedAt         time.Time
	FinishedAt        sql.NullTime
}

func (q *Queries) GetPlayerRecentMatches(ctx context.Context, arg GetPlayerRecentMatchesParams) ([]GetPlayerRecentMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerRecentMatches, arg.WhiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayerRecentMatchesRow
	for rows.Next() {
		var i GetPlayerRecentMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.WhiteID,
			&i.WhiteUsername,
			&i.BlackID,
			&i.BlackUsername,
			&i.TimeControl,
			&i.WhiteRatingBefore,
			&i.BlackRatingBefore,
			&i.WhiteRatingAfter,
			&i.BlackRatingAfter,
			&i.Result,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
