// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_moves.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMatchMove = `-- name: CreateMatchMove :one
INSERT INTO match_moves (
    match_id,
    move_number,
    player_id,
    san,
    uci,
    fen_after,
    white_time_ms,
    black_time_ms
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    match_id,
    move_number,
    player_id,
    san,
    uci,
    fen_after,
    white_time_ms,
    black_time_ms,
    created_at
`

type CreateMatchMoveParams struct {
	MatchID     uuid.UUID
	MoveNumber  int32
	PlayerID    uuid.UUID
	San         string
	Uci         string
	FenAfter    string
	WhiteTimeMs int64
	BlackTimeMs int64
}

func (q *Queries) CreateMatchMove(ctx context.Context, arg CreateMatchMoveParams) (MatchMove, error) {
	row := q.db.QueryRowContext(ctx, createMatchMove,
		arg.MatchID,
		arg.MoveNumber,
		arg.PlayerID,
		arg.San,
		arg.Uci,
		arg.FenAfter,
		arg.WhiteTimeMs,
		arg.BlackTimeMs,
	)
	var i MatchMove
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.MoveNumber,
		&i.PlayerID,
		&i.San,
		&i.Uci,
		&i.FenAfter,
		&i.WhiteTimeMs,
		&i.BlackTimeMs,
		&i.CreatedAt,
	)
	return i, err
}

const getLastMatchMove = `-- name: GetLastMatchMove :one
SELECT
    id,
    match_id,
    move_number,
    player_id,
    san,
    uci,
    fen_after,
    white_time_ms,
    black_time_ms,
    created_at
FROM match_moves
WHERE match_id = $1
ORDER BY move_number DESC
LIMIT 1
`

func (q *Queries) GetLastMatchMove(ctx context.Context, matchID uuid.UUID) (MatchMove, error) {
	row := q.db.QueryRowContext(ctx, getLastMatchMove, matchID)
	var i MatchMove
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.MoveNumber,
		&i.PlayerID,
		&i.San,
		&i.Uci,
		&i.FenAfter,
		&i.WhiteTimeMs,
		&i.BlackTimeMs,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchMove = `-- name: GetMatchMove :one
SELECT
    id,
    match_id,
    move_number,
    player_id,
    san,
    uci,
    fen_after,
    white_time_ms,
    black_time_ms,
    created_at
FROM match_moves
WHERE match_id = $1
  AND move_number = $2
`

type GetMatchMoveParams struct {
	MatchID    uuid.UUID
	MoveNumber int32
}

func (q *Queries) GetMatchMove(ctx context.Context, arg GetMatchMoveParams) (MatchMove, error) {
	row := q.db.QueryRowContext(ctx, getMatchMove, arg.MatchID, arg.MoveNumber)
	var i MatchMove
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.MoveNumber,
		&i.PlayerID,
		&i.San,
		&i.Uci,
		&i.FenAfter,
		&i.WhiteTimeMs,
		&i.BlackTimeMs,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchMoves = `-- name: GetMatchMoves :many
SELECT
    id,
    match_id,
    move_number,
    player_id,
    san,
    uci,
    fen_after,
    white_time_ms,
    black_time_ms,
    created_at
FROM match_moves
WHERE match_id = $1
ORDER BY move_number ASC
`

func (q *Queries) GetMatchMoves(ctx context.Context, matchID uuid.UUID) ([]MatchMove, error) {
	rows, err := q.db.QueryContext(ctx, getMatchMoves, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MatchMove
	for rows.Next() {
		var i MatchMove
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.MoveNumber,
			&i.PlayerID,
			&i.San,
			&i.Uci,
			&i.FenAfter,
			&i.WhiteTimeMs,
			&i.BlackTimeMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
