// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addConversationMember = `-- name: AddConversationMember :one
INSERT INTO conversation_members(
    conversation_id,
    user_id
)
VALUES(
    $1,
    $2
)
RETURNING conversation_id, user_id, joined_at
`

type AddConversationMemberParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) (ConversationMember, error) {
	row := q.db.QueryRowContext(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	var i ConversationMember
	err := row.Scan(&i.ConversationID, &i.UserID, &i.JoinedAt)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations(
    id,
    type
)
VALUES(
    $1,
    $2
)
RETURNING id, type, created_at
`

type CreateConversationParams struct {
	ID   uuid.UUID
	Type ConversationType
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.ID, arg.Type)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages(
    id,
    conversation_id,
    sender_id,
    content
)
VALUES(
    $1,
    $2,
    $3,
    $4
)
RETURNING id, conversation_id, sender_id, content, created_at, edited_at, deleted_at
`

type CreateMessageParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	Content        string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE
FROM conversations
WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
UPDATE messages
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const editMessage = `-- name: EditMessage :one
UPDATE messages
SET
    content = $2,
    edited_at = NOW()
WHERE id = $1
RETURNING id, conversation_id, sender_id, content, created_at, edited_at, deleted_at
`

type EditMessageParams struct {
	ID      uuid.UUID
	Content string
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, editMessage, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findDirectConversation = `-- name: FindDirectConversation :one
SELECT c.id, c.type, c.created_at
FROM conversations AS c
WHERE c.type = 'direct'
AND EXISTS (
    SELECT 1
    FROM conversation_members AS cm1
    WHERE cm1.conversation_id = c.id
      AND cm1.user_id = $1
)
AND EXISTS (
    SELECT 1
    FROM conversation_members AS cm2
    WHERE cm2.conversation_id = c.id
      AND cm2.user_id = $2
)
AND (
    SELECT COUNT(*)
    FROM conversation_members AS cm3
    WHERE cm3.conversation_id = c.id
) = 2
`

type FindDirectConversationParams struct {
	UserID   uuid.UUID
	UserID_2 uuid.UUID
}

func (q *Queries) FindDirectConversation(ctx context.Context, arg FindDirectConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, findDirectConversation, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, type, created_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const getConversationMembers = `-- name: GetConversationMembers :many
SELECT users.id, users.email, users.username, users.password, users.created_at, users.updated_at
FROM conversation_members
JOIN users
ON users.id = conversation_members.user_id
WHERE conversation_members.conversation_id = $1
`

func (q *Queries) GetConversationMembers(ctx context.Context, conversationID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastMessage = `-- name: GetLastMessage :one
SELECT id, conversation_id, sender_id, content, created_at, edited_at, deleted_at
FROM messages
WHERE conversation_id = $1
AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastMessage(ctx context.Context, conversationID uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getLastMessage, conversationID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, sender_id, content, created_at, edited_at, deleted_at
FROM messages
WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS(
    SELECT 1
    FROM conversation_members
    WHERE conversation_id = $1
    AND user_id = $2
)
`

type IsConversationMemberParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationMember = `-- name: ListConversationMember :many
SELECT
    users.id, users.email, users.username, users.password, users.created_at, users.updated_at
FROM conversation_members
JOIN users
ON users.id = conversation_members.user_id
WHERE conversation_members.conversation_id = $1
`

func (q *Queries) ListConversationMember(ctx context.Context, conversationID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listConversationMember, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT c.id, c.type, c.created_at
FROM conversations c
JOIN conversation_members cm
ON cm.conversation_id = c.id
WHERE cm.user_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) ListConversations(ctx context.Context, userID uuid.UUID) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(&i.ID, &i.Type, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, sender_id, content, created_at, edited_at, deleted_at
FROM messages
WHERE conversation_id = $1
AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $2
OFFSET $3
`

type ListMessagesParams struct {
	ConversationID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeConversationMember = `-- name: RemoveConversationMember :exec
DELETE
FROM conversation_members
WHERE conversation_id = $1
AND user_id = $2
`

type RemoveConversationMemberParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeConversationMember, arg.ConversationID, arg.UserID)
	return err
}
