// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPlayerRatings = `-- name: CreatePlayerRatings :exec
INSERT INTO player_ratings (
    user_id,
    rating_type,
    rating,
    rd,
    volatility,
    games_played
)
VALUES
    ($1, 'bullet', 1500.0, 350.0, 0.06, 0),
    ($1, 'blitz',  1500.0, 350.0, 0.06, 0),
    ($1, 'rapid',  1500.0, 350.0, 0.06, 0)
`

func (q *Queries) CreatePlayerRatings(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, createPlayerRatings, userID)
	return err
}

const createRatingHistory = `-- name: CreateRatingHistory :exec
INSERT INTO rating_history (
    user_id,
    match_id,
    rating_type,
    old_rating,
    new_rating,
    old_rd,
    new_rd,
    old_volatility,
    new_volatility
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateRatingHistoryParams struct {
	UserID        uuid.UUID
	MatchID       uuid.UUID
	RatingType    RatingType
	OldRating     float64
	NewRating     float64
	OldRd         float64
	NewRd         float64
	OldVolatility float64
	NewVolatility float64
}

func (q *Queries) CreateRatingHistory(ctx context.Context, arg CreateRatingHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createRatingHistory,
		arg.UserID,
		arg.MatchID,
		arg.RatingType,
		arg.OldRating,
		arg.NewRating,
		arg.OldRd,
		arg.NewRd,
		arg.OldVolatility,
		arg.NewVolatility,
	)
	return err
}

const getMatchRatingHistory = `-- name: GetMatchRatingHistory :many
SELECT
    id,
    user_id,
    match_id,
    rating_type,
    old_rating,
    new_rating,
    old_rd,
    new_rd,
    old_volatility,
    new_volatility,
    created_at
FROM rating_history
WHERE match_id = $1
ORDER BY user_id, rating_type
`

func (q *Queries) GetMatchRatingHistory(ctx context.Context, matchID uuid.UUID) ([]RatingHistory, error) {
	rows, err := q.db.QueryContext(ctx, getMatchRatingHistory, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RatingHistory
	for rows.Next() {
		var i RatingHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MatchID,
			&i.RatingType,
			&i.OldRating,
			&i.NewRating,
			&i.OldRd,
			&i.NewRd,
			&i.OldVolatility,
			&i.NewVolatility,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerRating = `-- name: GetPlayerRating :one
SELECT
    user_id,
    rating_type,
    rating,
    rd,
    volatility,
    games_played,
    created_at,
    updated_at
FROM player_ratings
WHERE user_id = $1
    AND rating_type = $2
`

type GetPlayerRatingParams struct {
	UserID     uuid.UUID
	RatingType RatingType
}

func (q *Queries) GetPlayerRating(ctx context.Context, arg GetPlayerRatingParams) (PlayerRating, error) {
	row := q.db.QueryRowContext(ctx, getPlayerRating, arg.UserID, arg.RatingType)
	var i PlayerRating
	err := row.Scan(
		&i.UserID,
		&i.RatingType,
		&i.Rating,
		&i.Rd,
		&i.Volatility,
		&i.GamesPlayed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerRatingHistory = `-- name: GetPlayerRatingHistory :many
SELECT
    id,
    user_id,
    match_id,
    rating_type,
    old_rating,
    new_rating,
    old_rd,
    new_rd,
    old_volatility,
    new_volatility,
    created_at
FROM rating_history
WHERE user_id = $1
  AND rating_type = $2
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type GetPlayerRatingHistoryParams struct {
	UserID     uuid.UUID
	RatingType RatingType
	Limit      int32
	Offset     int32
}

func (q *Queries) GetPlayerRatingHistory(ctx context.Context, arg GetPlayerRatingHistoryParams) ([]RatingHistory, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerRatingHistory,
		arg.UserID,
		arg.RatingType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RatingHistory
	for rows.Next() {
		var i RatingHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MatchID,
			&i.RatingType,
			&i.OldRating,
			&i.NewRating,
			&i.OldRd,
			&i.NewRd,
			&i.OldVolatility,
			&i.NewVolatility,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerRatings = `-- name: GetPlayerRatings :many
SELECT
    user_id,
    rating_type,
    rating,
    rd,
    volatility,
    games_played,
    created_at,
    updated_at
FROM player_ratings
WHERE user_id = $1
ORDER BY rating_type
`

func (q *Queries) GetPlayerRatings(ctx context.Context, userID uuid.UUID) ([]PlayerRating, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayerRating
	for rows.Next() {
		var i PlayerRating
		if err := rows.Scan(
			&i.UserID,
			&i.RatingType,
			&i.Rating,
			&i.Rd,
			&i.Volatility,
			&i.GamesPlayed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerRating = `-- name: UpdatePlayerRating :one
UPDATE player_ratings
SET
    rating = $3,
    rd = $4,
    volatility = $5,
    games_played = $6,
    updated_at = NOW()
WHERE user_id = $1
    AND rating_type = $2
RETURNING
    user_id,
    rating_type,
    rating,
    rd,
    volatility,
    games_played,
    created_at,
    updated_at
`

type UpdatePlayerRatingParams struct {
	UserID      uuid.UUID
	RatingType  RatingType
	Rating      float64
	Rd          float64
	Volatility  float64
	GamesPlayed int32
}

func (q *Queries) UpdatePlayerRating(ctx context.Context, arg UpdatePlayerRatingParams) (PlayerRating, error) {
	row := q.db.QueryRowContext(ctx, updatePlayerRating,
		arg.UserID,
		arg.RatingType,
		arg.Rating,
		arg.Rd,
		arg.Volatility,
		arg.GamesPlayed,
	)
	var i PlayerRating
	err := row.Scan(
		&i.UserID,
		&i.RatingType,
		&i.Rating,
		&i.Rd,
		&i.Volatility,
		&i.GamesPlayed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
