// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    user_id,
    refresh_token_hash,
    user_agent,
    ip_address,
    created_at,
    expires_at,
    max_expires_at,
    last_used_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, refresh_token_hash, user_agent, ip_address, created_at, expires_at, max_expires_at, last_used_at, revoked_at
`

type CreateSessionParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	RefreshTokenHash string
	UserAgent        sql.NullString
	IpAddress        sql.NullString
	CreatedAt        time.Time
	ExpiresAt        time.Time
	MaxExpiresAt     time.Time
	LastUsedAt       sql.NullTime
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.MaxExpiresAt,
		arg.LastUsedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= $1
OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, expires_at, max_expires_at, last_used_at, revoked_at
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, expires_at, max_expires_at, last_used_at, revoked_at
FROM sessions
WHERE refresh_token_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionForUpdateByTokenHash = `-- name: GetSessionForUpdateByTokenHash :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, expires_at, max_expires_at, last_used_at, revoked_at
FROM sessions
WHERE refresh_token_hash = $1
FOR UPDATE
`

func (q *Queries) GetSessionForUpdateByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionForUpdateByTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getValidSessionByTokenHash = `-- name: GetValidSessionByTokenHash :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, expires_at, max_expires_at, last_used_at, revoked_at
FROM sessions
WHERE refresh_token_hash = $1
AND revoked_at IS NULL
AND expires_at > $2
LIMIT 1
`

type GetValidSessionByTokenHashParams struct {
	RefreshTokenHash string
	ExpiresAt        time.Time
}

func (q *Queries) GetValidSessionByTokenHash(ctx context.Context, arg GetValidSessionByTokenHashParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getValidSessionByTokenHash, arg.RefreshTokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.MaxExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = $2
WHERE id = $1
`

type RevokeSessionParams struct {
	ID        uuid.UUID
	RevokedAt sql.NullTime
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.ID, arg.RevokedAt)
	return err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = $2
WHERE refresh_token_hash = $1
`

type RevokeSessionByTokenHashParams struct {
	RefreshTokenHash string
	RevokedAt        sql.NullTime
}

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, arg RevokeSessionByTokenHashParams) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByTokenHash, arg.RefreshTokenHash, arg.RevokedAt)
	return err
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE sessions
SET last_used_at = $2
WHERE id = $1
`

type UpdateSessionLastUsedParams struct {
	ID         uuid.UUID
	LastUsedAt sql.NullTime
}

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, arg UpdateSessionLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionLastUsed, arg.ID, arg.LastUsedAt)
	return err
}

const updateSessionToken = `-- name: UpdateSessionToken :exec
UPDATE sessions
SET
    refresh_token_hash = $2,
    expires_at = $3,
    last_used_at = $4
WHERE id = $1
`

type UpdateSessionTokenParams struct {
	ID               uuid.UUID
	RefreshTokenHash string
	ExpiresAt        time.Time
	LastUsedAt       sql.NullTime
}

func (q *Queries) UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionToken,
		arg.ID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.LastUsedAt,
	)
	return err
}
